#!/usr/bin/env python3
"""
Recursive Mod-Cycle Prime and Twin-Prime Generator

Rule:
    1. Continue every mod cycle already opened.
    2. A position reached by an earlier cycle is composite.
    3. An untouched position opens a new cycle and is prime.
    4. Two consecutive openings separated by 2 form a twin-prime pair.

No separate primality-checking function is used.
"""

from time import perf_counter


# ============================================================
# CONFIGURATION
# ============================================================

# Largest integer included in the recursive count.
MAX_NUMBER = 100_000_000

# Warning: printing every pair greatly slows large runs.
PRINT_EACH_TWIN_CENTRE = False


# ============================================================
# RECURSIVE MOD-CYCLE ENGINE
# ============================================================

def mark_future_completions(
    occupied: bytearray,
    cycle: int,
    limit: int,
) -> None:
    """
    Mark future positions reached by a newly opened mod cycle.

    Earlier cycles have already marked every smaller composite
    completion, so the first new position that this cycle needs
    to mark is cycle^2.
    """
    first_new_completion = cycle * cycle

    if first_new_completion > limit:
        return

    number_of_completions = (
        (limit - first_new_completion) // cycle
    ) + 1

    occupied[
        first_new_completion : limit + 1 : cycle
    ] = b"\x01" * number_of_completions


def generate_primes_and_twins(
    limit: int,
    print_each_twin: bool = False,
) -> dict:
    """
    Continue the recursive mod count through `limit`.

    Returns summary information about the prime openings and
    twin-prime centres generated by the process.
    """
    if limit < 2:
        return {
            "maximum_integer": limit,
            "prime_openings": 0,
            "twin_centres": 0,
            "first_twin": None,
            "last_twin": None,
        }

    # occupied[n] == 1:
    #     an earlier mod cycle reaches n, so n is composite.
    #
    # occupied[n] == 0:
    #     n is untouched and opens a new mod cycle.
    occupied = bytearray(limit + 1)
    occupied[0] = 1
    occupied[1] = 1

    previous_opening = None
    prime_openings = 0
    twin_centres = 0
    first_twin = None
    last_twin = None

    for number in range(2, limit + 1):
        if occupied[number]:
            continue

        # This untouched position opens a new mod cycle.
        prime_openings += 1

        # Two consecutive openings separated by 2 are twin primes.
        if (
            previous_opening is not None
            and number - previous_opening == 2
        ):
            centre = previous_opening + 1
            twin = (previous_opening, centre, number)

            twin_centres += 1
            last_twin = twin

            if first_twin is None:
                first_twin = twin

            if print_each_twin:
                print(
                    f"{previous_opening:,} : "
                    f"{centre:,} : "
                    f"{number:,}"
                )

        mark_future_completions(
            occupied,
            number,
            limit,
        )

        previous_opening = number

    return {
        "maximum_integer": limit,
        "prime_openings": prime_openings,
        "twin_centres": twin_centres,
        "first_twin": first_twin,
        "last_twin": last_twin,
    }


# ============================================================
# OUTPUT
# ============================================================

def format_twin(twin: tuple | None) -> str:
    """Format a left-centre-right twin structure."""
    if twin is None:
        return "none"

    left, centre, right = twin
    return f"{left:,} : {centre:,} : {right:,}"


def main() -> None:
    print("=" * 64)
    print("RECURSIVE MOD-CYCLE PRIME AND TWIN-PRIME GENERATOR")
    print("=" * 64)

    start_time = perf_counter()

    result = generate_primes_and_twins(
        MAX_NUMBER,
        PRINT_EACH_TWIN_CENTRE,
    )

    elapsed = perf_counter() - start_time

    print("\nSUMMARY")
    print("-" * 64)
    print(
        f"Maximum integer counted:  "
        f"{result['maximum_integer']:,}"
    )
    print(
        f"Prime cycles opened:      "
        f"{result['prime_openings']:,}"
    )
    print(
        f"Twin-prime centres:       "
        f"{result['twin_centres']:,}"
    )
    print(
        f"First twin structure:     "
        f"{format_twin(result['first_twin'])}"
    )
    print(
        f"Last twin structure:      "
        f"{format_twin(result['last_twin'])}"
    )
    print(f"Elapsed time:             {elapsed:.6f} seconds")


if __name__ == "__main__":
    main()
