#!/usr/bin/env python3
"""
RECURSIVE WHEEL PRIME/TWIN GENERATOR
WITH RADIX-8 METALLIC LOGIC TABLES

Purpose
-------
Generate every prime and every twin-prime pair up to N using only
internally generated recursive prime cycles.

The first few primes are generated by the same recursion and then used
to construct a wheel. The wheel skips every address already known to
belong to one of those completed prime cycles.

With wheel primes:

    2, 3, 5, 7, 11, 13

the wheel modulus is:

    2*3*5*7*11*13 = 30,030

and only:

    phi(30,030) = 5,760

residue states remain in each wheel cycle.

Candidate density:

    5,760 / 30,030 ≈ 0.191808

So the generator visits about 19.18% of the integer addresses, rather
than all integers or all odd integers.

No external primality tests are used.

Prime rule
----------
A wheel-admissible address reached by no earlier recursive prime cycle
opens as a new prime.

If it were composite, one of its earlier prime-factor cycles would
already have reached it.

Twin rule
---------
Generated primes arrive in increasing order. If two consecutive prime
openings differ by 2, the pair is a twin-prime pair.

Radix-8 logic
-------------
For each ordinary twin centre C=6n, n is represented in base 8.

This gives exact three-bit metallic address blocks and natural lift
boundaries:

    n < 8
    n < 8^2
    n < 8^3
    ...

The program counts twins in each recursive radix-8 shell without
retaining all twin pairs.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from math import gcd
from pathlib import Path
from time import perf_counter
import csv


# ============================================================
# CONFIGURATION
# ============================================================

MAX_NUMBER = 100_000_000

# Number of recursively generated primes used to build the wheel.
# 6 -> 2,3,5,7,11,13 and modulus 30,030.
WHEEL_PRIME_COUNT = 6

PRINT_SAMPLES = True
SAMPLE_SIZE = 10

PRINT_TWO_BLOCK_LOGIC_TABLE = True

WRITE_TWINS_CSV = False
CSV_PATH = Path("recursive_wheel_twin_addresses.csv")


# ============================================================
# SMALL INTERNAL BOOTSTRAP
# ============================================================

def recursive_bootstrap_primes(count: int) -> list[int]:
    """
    Generate the first `count` primes through recursive composite cycles.

    This uses the same untouched-address rule as the main generator.
    It does not use trial division or an external primality test.
    """
    if count <= 0:
        return []

    primes = [2]

    if count == 1:
        return primes

    # next composite completion -> odd cycle step
    events: dict[int, int] = {}
    candidate = 3

    while len(primes) < count:
        step = events.pop(candidate, None)

        if step is None:
            primes.append(candidate)

            square = candidate * candidate
            events[square] = 2 * candidate
        else:
            next_completion = candidate + step

            while next_completion in events:
                next_completion += step

            events[next_completion] = step

        candidate += 2

    return primes


# ============================================================
# RECURSIVE WHEEL
# ============================================================

@dataclass(frozen=True, slots=True)
class RecursiveWheel:
    primes: tuple[int, ...]
    modulus: int
    residues: tuple[int, ...]
    gaps: tuple[int, ...]
    phase_by_residue: dict[int, int]

    @classmethod
    def from_recursive_primes(
        cls,
        prime_count: int,
    ) -> "RecursiveWheel":
        generated = recursive_bootstrap_primes(prime_count)

        modulus = 1

        for prime in generated:
            modulus *= prime

        residues = tuple(
            residue
            for residue in range(1, modulus)
            if gcd(residue, modulus) == 1
        )

        gaps_list = [
            residues[index + 1] - residues[index]
            for index in range(len(residues) - 1)
        ]

        gaps_list.append(
            modulus + residues[0] - residues[-1]
        )

        phase_by_residue = {
            residue: index
            for index, residue in enumerate(residues)
        }

        return cls(
            primes=tuple(generated),
            modulus=modulus,
            residues=residues,
            gaps=tuple(gaps_list),
            phase_by_residue=phase_by_residue,
        )


# ============================================================
# PRIME-CYCLE GENERATOR
# ============================================================

@dataclass(slots=True)
class GeneratorStats:
    wheel_candidates_visited: int = 0
    prime_openings: int = 0
    cycle_openings: int = 0
    cycle_completions: int = 0
    collision_advances: int = 0
    maximum_active_events: int = 0


class RecursiveWheelPrimeCycles:
    """
    Incremental prime cycles restricted to wheel-admissible addresses.

    events maps:
        next composite completion -> (prime, multiplier-wheel phase)

    Each active prime retains only its next relevant completion.
    """

    def __init__(
        self,
        maximum: int,
        wheel: RecursiveWheel,
    ) -> None:
        if maximum < 2:
            raise ValueError("maximum must be at least 2")

        self.maximum = maximum
        self.wheel = wheel
        self.events: dict[int, tuple[int, int]] = {}
        self.stats = GeneratorStats()

    def _record_event_count(self) -> None:
        active = len(self.events)

        if active > self.stats.maximum_active_events:
            self.stats.maximum_active_events = active

    def _advance_cycle(
        self,
        completion: int,
        prime: int,
        multiplier_phase: int,
    ) -> None:
        """
        Advance a prime cycle through the wheel multiplier pattern.

        If two prime cycles reach the same composite address, only one
        event is needed there. The other cycle advances recursively to
        its following completion.
        """
        gaps = self.wheel.gaps
        phase_count = len(gaps)

        next_completion = (
            completion
            + prime * gaps[multiplier_phase]
        )

        multiplier_phase += 1

        if multiplier_phase == phase_count:
            multiplier_phase = 0

        while next_completion in self.events:
            next_completion += (
                prime * gaps[multiplier_phase]
            )

            multiplier_phase += 1

            if multiplier_phase == phase_count:
                multiplier_phase = 0

            self.stats.collision_advances += 1

        if next_completion <= self.maximum:
            self.events[next_completion] = (
                prime,
                multiplier_phase,
            )
            self._record_event_count()

    def primes(self):
        """Yield every prime through maximum in increasing order."""
        for prime in self.wheel.primes:
            if prime <= self.maximum:
                self.stats.prime_openings += 1
                yield prime

        if self.maximum <= self.wheel.primes[-1]:
            return

        gaps = self.wheel.gaps
        phase_count = len(gaps)

        # Begin at wheel residue 1, then advance until past the largest
        # wheel prime.
        candidate = 1
        candidate_phase = 0

        while candidate <= self.wheel.primes[-1]:
            candidate += gaps[candidate_phase]
            candidate_phase += 1

            if candidate_phase == phase_count:
                candidate_phase = 0

        while candidate <= self.maximum:
            self.stats.wheel_candidates_visited += 1

            event = self.events.pop(
                candidate,
                None,
            )

            if event is None:
                # This address survived every earlier recursive cycle.
                prime = candidate
                self.stats.prime_openings += 1
                yield prime

                square = prime * prime

                if square <= self.maximum:
                    multiplier_phase = (
                        self.wheel.phase_by_residue[
                            prime % self.wheel.modulus
                        ]
                    )

                    self.events[square] = (
                        prime,
                        multiplier_phase,
                    )
                    self.stats.cycle_openings += 1
                    self._record_event_count()
            else:
                self.stats.cycle_completions += 1

                prime, multiplier_phase = event

                self._advance_cycle(
                    completion=candidate,
                    prime=prime,
                    multiplier_phase=multiplier_phase,
                )

            candidate += gaps[candidate_phase]
            candidate_phase += 1

            if candidate_phase == phase_count:
                candidate_phase = 0


# ============================================================
# METALLIC ADDRESS
# ============================================================

LAYER_BY_WEIGHT = {
    0: "G",
    1: "S",
    2: "B",
    3: "L",
}


def address_depth(centre_index: int) -> int:
    """Number of three-bit/base-8 blocks required."""
    return max(
        1,
        (centre_index.bit_length() + 2) // 3,
    )


def three_bit_address(centre_index: int) -> str:
    """Exact base-8 address rendered as three-bit blocks."""
    depth = address_depth(centre_index)

    return "|".join(
        format(
            (centre_index >> (3 * level)) & 0b111,
            "03b",
        )
        for level in reversed(range(depth))
    )


def metallic_address(centre_index: int) -> str:
    """
    Indexed metallic address.

    Positional level 1 is the least-significant three-bit block.
    """
    depth = address_depth(centre_index)
    tokens: list[str] = []

    for position in reversed(range(depth)):
        digit = (
            centre_index >> (3 * position)
        ) & 0b111

        weight = digit.bit_count()
        local_level = position + 1
        metallic_index = local_level + weight

        tokens.append(
            f"{LAYER_BY_WEIGHT[weight]}:M{metallic_index}"
        )

    return "|".join(tokens)


def trailing_lift_blocks(centre_index: int) -> int:
    """Number of consecutive least-significant 111 blocks."""
    count = 0
    value = centre_index

    while value & 0b111 == 0b111:
        count += 1
        value >>= 3

    return count


# ============================================================
# TWIN STATISTICS
# ============================================================

@dataclass(frozen=True, slots=True)
class TwinSample:
    lower: int
    centre: int
    upper: int
    centre_index: int | None


class SampleWindow:
    def __init__(self, size: int) -> None:
        self.size = size
        self.first: list[TwinSample] = []
        self.last: list[TwinSample] = []

    def add(self, sample: TwinSample) -> None:
        if len(self.first) < self.size:
            self.first.append(sample)

        self.last.append(sample)

        if len(self.last) > self.size:
            self.last.pop(0)


@dataclass(slots=True)
class TwinLogicStats:
    total_twins: int = 0
    ordinary_twins: int = 0
    exceptional_twins: int = 0

    depth_counts: Counter | None = None
    low_digit_counts: Counter | None = None
    layer_counts: Counter | None = None
    trailing_lift_counts: Counter | None = None
    low_two_block_counts: list[int] | None = None

    def __post_init__(self) -> None:
        self.depth_counts = Counter()
        self.low_digit_counts = Counter()
        self.layer_counts = Counter()
        self.trailing_lift_counts = Counter()

        # Exact two-block suffix table: 64 fixed counters.
        if self.low_two_block_counts is None:
            self.low_two_block_counts = [0] * 64

    def record(
        self,
        lower: int,
        upper: int,
    ) -> TwinSample:
        centre = (lower + upper) // 2

        self.total_twins += 1

        if centre % 6 != 0:
            self.exceptional_twins += 1

            return TwinSample(
                lower=lower,
                centre=centre,
                upper=upper,
                centre_index=None,
            )

        self.ordinary_twins += 1
        centre_index = centre // 6

        depth = address_depth(centre_index)
        low_digit = centre_index & 0b111
        weight = low_digit.bit_count()

        self.depth_counts[depth] += 1
        self.low_digit_counts[low_digit] += 1
        self.layer_counts[LAYER_BY_WEIGHT[weight]] += 1
        self.trailing_lift_counts[
            trailing_lift_blocks(centre_index)
        ] += 1

        self.low_two_block_counts[
            centre_index & 0b111111
        ] += 1

        return TwinSample(
            lower=lower,
            centre=centre,
            upper=upper,
            centre_index=centre_index,
        )


# ============================================================
# OUTPUT HELPERS
# ============================================================

def print_sample(sample: TwinSample) -> None:
    print(
        f"{sample.lower:,} : "
        f"{sample.centre:,} : "
        f"{sample.upper:,}"
    )

    if sample.centre_index is None:
        print(
            "    exceptional pair outside ordinary 6n centres"
        )
        return

    print(
        f"    centre index: "
        f"{sample.centre_index:,}"
    )
    print(
        f"    three-bit address: "
        f"{three_bit_address(sample.centre_index)}"
    )
    print(
        f"    metallic address:  "
        f"{metallic_address(sample.centre_index)}"
    )


def print_counter(
    title: str,
    counter: Counter,
) -> None:
    print(f"\n{title}:")

    for key, value in sorted(counter.items()):
        print(
            f"  {key}: {value:,}"
        )


def print_radix8_shell_table(
    logic: TwinLogicStats,
) -> None:
    print("\nRadix-8 lift shells:")
    print(
        "depth | centre-index interval | twins in shell | "
        "cumulative ordinary twins"
    )

    cumulative = 0

    for depth in sorted(logic.depth_counts):
        shell_count = logic.depth_counts[depth]
        cumulative += shell_count

        lower = 0 if depth == 1 else 8 ** (depth - 1)
        upper = 8 ** depth

        print(
            f"{depth:>5} | "
            f"[{lower:,}, {upper:,}) | "
            f"{shell_count:>14,} | "
            f"{cumulative:>25,}"
        )


def print_two_block_table(
    counts: list[int],
) -> None:
    print("\nTwo-block suffix logic table:")
    print(
        "Rows are the higher three-bit block; "
        "columns are the lower three-bit block."
    )

    print(
        "       "
        + " ".join(
            f"{column:03b}".rjust(8)
            for column in range(8)
        )
    )

    for row in range(8):
        values = counts[
            row * 8:
            (row + 1) * 8
        ]

        print(
            f"{row:03b}  "
            + " ".join(
                f"{value:8,d}"
                for value in values
            )
        )


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    print("=" * 86)
    print("RECURSIVE WHEEL PRIME/TWIN GENERATOR")
    print("=" * 86)
    print(f"Maximum number:          {MAX_NUMBER:,}")
    print(f"Recursive wheel primes: {WHEEL_PRIME_COUNT}")

    wheel_start = perf_counter()

    wheel = RecursiveWheel.from_recursive_primes(
        WHEEL_PRIME_COUNT
    )

    wheel_elapsed = perf_counter() - wheel_start

    print(
        "Generated wheel primes:  "
        + ", ".join(
            str(prime)
            for prime in wheel.primes
        )
    )
    print(
        f"Wheel modulus:           "
        f"{wheel.modulus:,}"
    )
    print(
        f"Admissible wheel states: "
        f"{len(wheel.residues):,}"
    )
    print(
        f"Wheel density:           "
        f"{len(wheel.residues) / wheel.modulus:.6%}"
    )
    print(
        f"Wheel build time:        "
        f"{wheel_elapsed:.6f} seconds"
    )
    print("External prime tests:    none")
    print("Full Boolean sieve:      none")
    print()

    generator = RecursiveWheelPrimeCycles(
        maximum=MAX_NUMBER,
        wheel=wheel,
    )

    logic = TwinLogicStats()
    samples = SampleWindow(
        SAMPLE_SIZE
    )

    csv_file = None
    csv_writer = None

    if WRITE_TWINS_CSV:
        csv_file = CSV_PATH.open(
            "w",
            newline="",
            encoding="utf-8",
        )
        csv_writer = csv.writer(csv_file)
        csv_writer.writerow(
            [
                "lower_prime",
                "centre",
                "upper_prime",
                "centre_index",
                "three_bit_address",
                "metallic_address",
            ]
        )

    start = perf_counter()

    previous_prime = None
    highest_twin: TwinSample | None = None

    try:
        for prime in generator.primes():
            if (
                previous_prime is not None
                and prime - previous_prime == 2
            ):
                sample = logic.record(
                    previous_prime,
                    prime,
                )

                samples.add(sample)
                highest_twin = sample

                if csv_writer is not None:
                    if sample.centre_index is None:
                        bit_address = ""
                        metal_address = ""
                    else:
                        bit_address = three_bit_address(
                            sample.centre_index
                        )
                        metal_address = metallic_address(
                            sample.centre_index
                        )

                    csv_writer.writerow(
                        [
                            sample.lower,
                            sample.centre,
                            sample.upper,
                            (
                                ""
                                if sample.centre_index is None
                                else sample.centre_index
                            ),
                            bit_address,
                            metal_address,
                        ]
                    )

            previous_prime = prime
    finally:
        if csv_file is not None:
            csv_file.close()

    elapsed = perf_counter() - start

    odd_baseline = (MAX_NUMBER - 1) // 2
    integer_baseline = max(0, MAX_NUMBER - 1)

    visited = generator.stats.wheel_candidates_visited

    print("=" * 86)
    print("SUMMARY")
    print("=" * 86)
    print(
        f"Prime openings:             "
        f"{generator.stats.prime_openings:,}"
    )
    print(
        f"Twin-prime pairs:           "
        f"{logic.total_twins:,}"
    )
    print(
        f"Ordinary 6n twins:          "
        f"{logic.ordinary_twins:,}"
    )
    print(
        f"Exceptional twins:          "
        f"{logic.exceptional_twins:,}"
    )
    print(
        f"Wheel addresses visited:    "
        f"{visited:,}"
    )
    print(
        f"Odd-address baseline:       "
        f"{odd_baseline:,}"
    )
    print(
        f"Reduction from odd scan:    "
        f"{1 - visited / odd_baseline:.6%}"
    )
    print(
        f"Reduction from integer scan:"
        f" {1 - visited / integer_baseline:.6%}"
    )
    print(
        f"Prime cycles opened:        "
        f"{generator.stats.cycle_openings:,}"
    )
    print(
        f"Cycle completions:          "
        f"{generator.stats.cycle_completions:,}"
    )
    print(
        f"Collision advances:         "
        f"{generator.stats.collision_advances:,}"
    )
    print(
        f"Maximum active events:      "
        f"{generator.stats.maximum_active_events:,}"
    )
    print(
        f"Elapsed time:               "
        f"{elapsed:.6f} seconds"
    )

    if highest_twin is not None:
        print("\nHighest generated twin:")
        print_sample(highest_twin)
        print(
            f"    rank among generated twins: "
            f"{logic.total_twins:,}"
        )
        print(
            f"    twin pairs before it:        "
            f"{logic.total_twins - 1:,}"
        )

    print_radix8_shell_table(logic)

    print_counter(
        "Least-significant exact three-bit state",
        logic.low_digit_counts,
    )

    print_counter(
        "Least-significant metallic layer",
        logic.layer_counts,
    )

    print_counter(
        "Trailing completed 111 lift blocks",
        logic.trailing_lift_counts,
    )

    if PRINT_TWO_BLOCK_LOGIC_TABLE:
        print_two_block_table(
            logic.low_two_block_counts
        )

    if PRINT_SAMPLES:
        print("\n" + "=" * 86)
        print("FIRST SAMPLE")
        print("=" * 86)

        for sample in samples.first:
            print_sample(sample)

        print("\n" + "=" * 86)
        print("LAST SAMPLE")
        print("=" * 86)

        for sample in samples.last:
            print_sample(sample)

    if WRITE_TWINS_CSV:
        print(
            f"\nCSV written to: "
            f"{CSV_PATH.resolve()}"
        )

    print("\nInterpretation:")
    print(
        "The recursive wheel removes addresses belonging to the "
        "internally generated cycles of its wheel primes."
    )
    print(
        "The remaining recursive cycles generate every surviving prime."
    )
    print(
        "The radix-8 shell table counts twin addresses at each "
        "self-similar lift scale without retaining all twins."
    )
    print(
        "The next compression problem is to derive those shell and "
        "suffix counts directly from the recursive state transition."
    )


if __name__ == "__main__":
    main()
